### ISSUE TITLE
option to toggle two inputbox for start and end time.

### ISSUE THREAD

**Issue by tobujin** [technikhil314/angular-2-daterangepicker#31]
I think toggling time-picker options is convenient.
But sometimes i feels to toggle the two input-boxes on the top.
if then , it will looks more smart , i think.
Thanks.

**Comment by nikhil-001mehta** [comment]
so you do not want the input boxes in flyout. i can add option for that

**Comment by technikhil314** [comment]
Closing this as there is no confirmation on what is the exact requirement.
