### ISSUE TITLE
The demo get 404 returned and the module could not use.

### ISSUE THREAD

**Issue by MUYUSY** [technikhil314/angular-2-daterangepicker#35]
Is there any problem?

**Comment by MUYUSY** [comment]
I thought there is an error in component in 1.1.50, at line 77 of daterangepicker.component.ts where "window.Node" will get an error, while 1.1.49 is ok.
Also the demo page could not visit.

**Comment by technikhil314** [comment]
@MUYUSY Not sure if you are the only one facing the issue. I have tried it on different browsers and OSs. But I am not able to reproduce it.

**Comment by technikhil314** [comment]
@MUYUSY Thanks for reporting this issue. I have fixed it in v.1.1.51
